apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-js
  namespace: app-dev
spec:
  ingressClassName: nginx
  tls:
    - hosts: [hello.dev.example.com]
      secretName: tls-wildcard-example
  rules:
    - host: hello.dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-js
                port: { number: 80 }
